Redi.Deliverer/Models/AuthorizationViewModel.cs
using Redi.Domain.Models.Account;

namespace Redi.Deliverer.Models
{
    public class AuthorizationViewModel
    {
        public IReadOnlyCollection<DelivererPreview> Deliverers { get; set; }
        public SignInDTO SignInDTO { get; set; }
    }
}

Redi.Deliverer/Models/ChatDetailsViewModel.cs
namespace Redi.Deliverer.Models
{
    public class ChatDetailsViewModel
    {
        public Guid ChatId { get; set; }

        public IReadOnlyCollection<ChatMessageViewModel> Messages { get; set; }
    }

    public class ChatMessageViewModel
    {
        public string Sender { get; set; }

        public string Text { get; set; }

        public bool IsUserSender { get; set; }
    }
}

Redi.Deliverer/Models/ChatsViewModel.cs
using Redi.Domain.Models.Chats;

namespace Redi.Deliverer.Models
{
    public class ChatsViewModel
    {
        public IReadOnlyCollection<ChatPreview> Chats { get; set; }
    }
}

Redi.Deliverer/Models/DelivererPreview.cs
namespace Redi.Deliverer.Models
{
    public class DelivererPreview
    {
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Redi.Deliverer/Models/DeliveriesViewModel.cs
using Redi.Domain.Models.Delivery;

namespace Redi.Deliverer.Models
{
    public class DeliveriesViewModel
    {
        public IReadOnlyCollection<DeliveryDto> Deliveries { get; set; }
    }
}

Redi.Deliverer/Models/DeliveryViewModel.cs
using Redi.DataAccess.Data;
using Redi.Domain.Models.Delivery;

namespace Redi.Deliverer.Models
{
    public class DeliveryViewModel
    {
        public int Id { get; set; }
        public string TrackNumber { get; set; }
        public IReadOnlyCollection<DeliveryStatus> Statuses { get; set; }
        public bool CanUpdateStatus => Statuses.Where(s => s.CreatedDate.HasValue).Count() != Enum.GetValues(typeof(DeliveryStatuses)).Length;
    }
}

Redi.Deliverer/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Redi.Deliverer.Models;
using Redi.Domain.Models.Account;
using Redi.Domain.Services;
using System;
using System.Security.Claims;

namespace Redi.Deliverer.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly ILogger<AuthorizationController> _logger;
        private readonly IRediApiProvider _provider;
        public AuthorizationController(ILogger<AuthorizationController> logger, IRediApiProvider provider)
        {
            _logger = logger;
            _provider = provider;
        }

        public IActionResult Index()
        {
            var deliverers = new List<DelivererPreview>
            {
                new()
                {
                    Fullname = "Erminie Capini",
                    Email = "ecapini0@japanpost.jp",
                    Password = "qKPGUj"
                },
                new()
                {
                    Fullname = "Dalston Batteson",
                    Email = "dbattesong@state.tx.us",
                    Password = "thMgNwS)ZyB"
                },
                new()
                {
                    Fullname = "Herrick Exroll",
                    Email = "hexrollp@uol.com.br",
                    Password = "v1AQnaed{H0"
                },
                new()
                {
                    Fullname = "Klement Ever",
                    Email = "kever10@marketwatch.com",
                    Password = "Vq4Ue%pDI"
                },
            };

            var viewModel = new AuthorizationViewModel()
            {
                Deliverers = deliverers,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Authorize(SignInDTO signIn)
        {
            var result = await _provider.Authorize(signIn);

            if (!result.Success)
                return RedirectToAction(nameof(Index));

            HttpContext.Session.SetString("Token", result.Token);

            return RedirectToActionPermanent(nameof(Index), "Home");
        }
    }
}

Redi.Deliverer/Controllers/ChatsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Redi.Application.Models;
using Redi.DataAccess.Data.Entities.Users;
using Redi.Deliverer.Models;
using Redi.Domain.Models.Chats;
using Redi.Domain.Services;

namespace Redi.Deliverer.Controllers
{
    [Route("[controller]")]
    public class ChatsController : Controller
    {
        private readonly IRediApiProvider _provider;

        public ChatsController(IRediApiProvider provider)
        {
            _provider = provider;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var chats = await _provider.Get<IReadOnlyCollection<ChatPreview>>("api/chats");

            var viewModel = new ChatsViewModel()
            {
                Chats = chats
            };

            return View(viewModel);
        }

        [HttpGet("ChatDetails")]
        public async Task<IActionResult> ChatDetails(Guid chatId)
        {
            var chat = await _provider.Get<ChatDto>($"api/chats/{chatId}");

            var test = User;
            return PartialView(new ChatDetailsViewModel
            {
                ChatId = chatId,
                Messages = chat.Messages.Select(x => new ChatMessageViewModel
                {
                    Sender = x.Sender,
                    Text = x.Text,
                    IsUserSender = x.IsUserSender,
                }).ToArray()
            });
        }
    }
}

Redi.Deliverer/Controllers/DeliveryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Redi.Application.Helpers;
using Redi.Deliverer.Models;
using Redi.Domain.Models.Delivery;
using Redi.Domain.Models.Delivery.Enums;
using Redi.Domain.Services;

namespace Redi.Deliverer.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly IRediApiProvider _provider;
        public DeliveryController(IRediApiProvider provider)
        {
            _provider = provider;
        }

        public async Task<IActionResult> Index()
        {
            var deliveries = await _provider.Get<IReadOnlyCollection<DeliveryDto>>("/api/Deliveries/all");

            var model = new DeliveriesViewModel()
            {
                Deliveries = deliveries
            };

            return View(model);
        }

        public async Task<IActionResult> Package(int deliveryId)
        {
            var trackInfo = await _provider.Get<PackageTrackDTO?>($"api/Deliveries/track?deliveryId={deliveryId}");

            if (trackInfo is null)
                return RedirectToAction("Index");

            var statuses = await FillMock(trackInfo.Statuses);

            var viewmodel = new DeliveryViewModel()
            {
                Id = trackInfo.Id,
                TrackNumber = trackInfo.TrackNumber,
                Statuses = statuses
            };

            return View(viewmodel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePackageStatus(int deliveryId)
        {
            await _provider.Head($"api/Deliveries/nextStatus?deliveryId={deliveryId}");

            return await Package(deliveryId);
        }

        private async Task<IReadOnlyCollection<DeliveryStatus>> FillMock(IReadOnlyCollection<DeliveryStatus> owned)
        {
            var mock = Enum.GetValues<DeliveryStatuses>();

            var statuses = new List<DeliveryStatus>(owned);

            var missing = mock.Select(s => new DeliveryStatus
            {
                Name = s.Description()
            }).Where(s => !owned.Any(p => p.Name == s.Name)).ToArray();

            statuses.AddRange(missing);

            return statuses;
        }
    }
}

Redi.Deliverer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Redi.Deliverer.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Redi.Deliverer/Views/Authorization/Index.cshtml
@model AuthorizationViewModel
@{
    ViewData["Title"] = "Авторизация";
}

<div>Выберите доставщика</div>
@{
    int i = 0;
}
@foreach (var deliverer in Model.Deliverers)
{
    <button form="@i-form" class="rounded btn btn-primary mb-2" type="submit">
        <form id="@i-form" method="post" action="/Authorization/Authorize">
            <div>
                @deliverer.Fullname
            </div>

            @Html.LabelFor(m => m.SignInDTO.Email, deliverer.Email)
            @Html.HiddenFor(m => m.SignInDTO.Password, deliverer.Password)

            <input hidden asp-for="SignInDTO.Email" name="Email" value="@deliverer.Email" />
            <input hidden asp-for="SignInDTO.Password" name="Password" value="@deliverer.Password" />
        </form>
        @{
            i++;
        }
    </button>
}

Redi.Deliverer/Views/Chats/ChatDetails.cshtml
@model ChatDetailsViewModel

Redi.Deliverer/Views/Chats/Index.cshtml
@model ChatsViewModel

<div>Чаты:</div>
<div class="col-2">
    @foreach (var chat in Model.Chats)
    {
        <a class="btn btn-outline-primary d-flex chat-btn" data-chatId="@chat.Id">
            <div class="rounded-circle">
                <img src="@chat.InterlocutorPhoto" />
            </div>
            <div>
                <div>
                    @chat.InterlocutorFullname
                </div>
                <div>
                    @chat.LastMessage
                </div>
            </div>
        </a>
    }
</div>
<div class="col-10">
    <div id="chat-container"></div>
</div>

@section Scripts{
    <script>
        let $chatContainer = $('#chat-container');
        $('.chat-btn').on('click', async function () {
            let chatId = $(this).data('chatid');
            
            let response = await $.ajax({
                url: '@Url.Action("ChatDetails", "Chats")?chatId=' + chatId
            });

            $chatContainer.html(response);
        });
    </script>
}

Redi.Deliverer/Views/Delivery/Index.cshtml
@model DeliveriesViewModel

<div class="d-flex flex-column">

    @foreach (var delivery in Model.Deliveries)
    {
        <a class="btn btn-primary m-2" href="@Url.Action("Package","Delivery", new {DeliveryId = delivery.Id})">
            @delivery.TrackNumber
        </a>
    }
</div>

Redi.Deliverer/Views/Delivery/Package.cshtml
@model DeliveryViewModel

<div>
    <div class="mb-2">Трэк-номер:</div>
    <div class="mb-4">@Model.TrackNumber</div>
    <div class="mb-2">Статусы доставки:</div>
    @foreach (var status in Model.Statuses)
    {
        <div class="border-bottom">
            <div>
                @status.Name
            </div>
            <div class="mb-2">
                @if (status.CreatedDate.HasValue)
                {
                    <div>@status.CreatedDate</div>
                }
                else
                {
                    <div>-</div>
                }
            </div>
        </div>
    }
    @if (Model.CanUpdateStatus)
    {
        <button class="btn btn-primary mt-5" onclick="updateStatus()">
            Поставить следующий статус
        </button>
    }
    else
    {
        <button class="btn btn-primary mt-5 disabled">
            Больше статус менять нельзя
        </button>
    }
</div>

@section scripts {
    <script type="text/javascript">
        function updateStatus() {
            $.ajax({
                type: 'POST',
                url: "/Delivery/UpdatePackageStatus",
                data: { 'deliveryId': @Model.Id },
                success: function () {
                    window.location.href = '@Url.Action("Package", "Delivery", new { DeliveryId = Model.Id })';
                },
                error: function (error) {
                    alert(error)
                }
            });
        }
    </script>
}

Redi.Deliverer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Меню";
}

<div class="container">
    <div class="row">
        <div class="p-2 col-6">
            <a class="btn btn-primary w-100" href="@Url.Action("Index", "Chats")">
                <div class="col d-flex justify-content-center">
                    <img style="height:100px;" src="~/icons/chat_icon.svg" />
                </div>
                Чаты
            </a>
        </div>
        <div class="p-2 col-6">
            <a class="btn btn-primary w-100" href="@Url.Action("Index", "Delivery")">
                <div class="col d-flex justify-content-center">
                    <img style="height:100px" src="~/icons/delivery_icon.svg" />
                </div>
                Доставки
            </a>
        </div>
    </div>
</div>

Redi.Deliverer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Redi.Deliverer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="visually-hidden navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Authorization" asp-action="Index">Сменить пользователя</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chats" asp-action="Index">Chats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Delivery" asp-action="Index">Delivery</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>